set(rust_target "gnullvm")
set(ffmpeg_extra_libs "-lc++")
set(mpv_lto_mode "-Db_lto_mode=thin")
if(CLANG_PACKAGES_LTO)
    set(cargo_lto_rustflags "CARGO_PROFILE_RELEASE_LTO=thin
                             RUSTFLAGS='-C linker-plugin-lto -C embed-bitcode -C lto=thin'")
    set(ffmpeg_lto "--enable-lto=thin")
    if(NOT LLVM_ARCH_HAS_AVX)
        set(zlib_nlto "LTO=0")
    endif()
endif()

set(dlltool_image "i386:x86-64")
set(vulkan_asm "-DUSE_GAS=ON")
set(openssl_target "mingw64")
set(openssl_ec_opt "enable-ec_nistp_64_gcc_128")
set(xxhash_dispatch "-DDISPATCH=ON")
set(xxhash_cflags "-DXXH_X86DISPATCH_ALLOW_AVX=1")
