set(llvm_wrapper "llvm-wrapper")
set(llvm_libcxx "llvm-libcxx")
set(cfguard "--enable-cfguard")
set(opt "-O3")
if(LLVM_CCACHE_BUILD)
    set(llvm_ccache "-DLLVM_CCACHE_BUILD=ON -DLLVM_CCACHE_DIR=${LLVM_CCACHE_DIR} -DLLVM_CCACHE_MAXSIZE=${LLVM_CCACHE_MAXSIZE}")
endif()
if(LLVM_ENABLE_LTO STREQUAL "Thin")
    set(llvm_lto "-flto=thin -fwhole-program-vtables -fsplit-lto-unit")
endif()
if(LLVM_ENABLE_PGO STREQUAL "GEN")
    set(llvm_pgo "-fprofile-generate=${LLVM_PROFILE_DATA_DIR} -fprofile-update=atomic")
elseif(LLVM_ENABLE_PGO STREQUAL "CSGEN")
    set(llvm_pgo "-fcs-profile-generate=${LLVM_PROFILE_DATA_DIR} -fprofile-update=atomic -fprofile-use=${LLVM_PROFDATA_FILE}")
elseif(LLVM_ENABLE_PGO STREQUAL "USE")
    set(llvm_pgo "-fprofile-use=${LLVM_PROFDATA_FILE}")
endif()

set(ld_m_flag "i386pep")
set(crt_lib "--disable-lib32 --enable-lib64")
set(LIBOMP_ASMFLAGS_M64 "-DLIBOMP_ASMFLAGS=-m64")
set(M_TUNE "generic")
set(cfi "-mguard=cf")
if (LLVM_ARCH STREQUAL "x86-64")
    unset(cfi)
    unset(opt)
endif()
