name: mpv clang
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Run custom command before building'
        required: false
        type: string
      github_release:
        description: 'Upload to Github release'
        required: false
        default: true
        type: boolean

jobs:
  build_mpv:
    name: Building mpv (${{ matrix.llvm_arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - llvm_arch: x86-64-v3
            x86_64_level: v3
          - llvm_arch: znver3
            x86_64_level: znver3
    env:
      BIT: x86_64
      BUILD_DIR: build_x86_64-${{ matrix.x86_64_level }}
    steps:
      - name: Installing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git ninja-build cmake automake pkgconf libtool libtool-bin clang llvm lld libc++1 libc++abi1 libgmp-dev libmpfr-dev libmpc-dev libgcrypt-dev python3-pip unzip p7zip-full curl ccache gettext nasm
          pip3 install --break-system-packages meson mako jsonschema

      - name: Setup git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@main
        with:
          ref: master

      - name: Loading clang sysroot cache
        uses: actions/cache/restore@main
        with:
          path: |
            clang_root
          key: ${{ secrets.CACHE_VERSION }}-clang_root-${{ github.run_id }}
          restore-keys: |
            ${{ secrets.CACHE_VERSION }}-clang_root

      - name: Loading repository cache
        uses: actions/cache/restore@main
        with:
          path: src_packages
          key: ${{ secrets.CACHE_VERSION }}-repository-${{ github.run_id }}
          restore-keys: |
            ${{ secrets.CACHE_VERSION }}-repository

      - name: Loading ${{ matrix.x86_64_level }} toolchain cache
        uses: actions/cache/restore@main
        with:
          path: |
            ${{ env.BUILD_DIR }}
          key: ${{ secrets.CACHE_VERSION }}-clang-${{ matrix.x86_64_level }}_toolchain-${{ github.run_id }}
          restore-keys: |
            ${{ secrets.CACHE_VERSION }}-clang-${{ matrix.x86_64_level }}_toolchain

      - name: Running custom command
        if: ${{ github.event.inputs.command != '' }}
        continue-on-error: true
        run: ${{ github.event.inputs.command }}

      - name: Configuring CMake & Downloading source
        run: |
          cmake -DTARGET_ARCH=$BIT-w64-mingw32 -DCOMPILER_TOOLCHAIN=clang -DLLVM_ARCH=${{ matrix.llvm_arch }} -DCMAKE_INSTALL_PREFIX=$PWD/clang_root -DMINGW_INSTALL_PREFIX=$PWD/$BUILD_DIR/$BIT-${{ matrix.x86_64_level }}-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -DRUSTUP_LOCATION=$PWD/clang_root/install_rustup -DENABLE_CCACHE=ON -DCLANG_PACKAGES_LTO=ON -G Ninja --fresh -B $BUILD_DIR -S $PWD
          ninja -C $BUILD_DIR download || true

      - name: Building mpv
        id: build_mpv_step
        run: |
          ninja -C $BUILD_DIR update
          ninja -C $BUILD_DIR mpv

      - name: Packaging mpv
        run: |
          mkdir -p release_${{ matrix.x86_64_level }}
          ninja -C $BUILD_DIR mpv-packaging; mv $BUILD_DIR/mpv*.7z release_${{ matrix.x86_64_level }} || true

      - name: Copying ffmpeg
        run: |
          hash=$(git -C src_packages/ffmpeg rev-parse --short HEAD)
          7z a -m0=lzma2 -mx=9 -ms=on release_${{ matrix.x86_64_level }}/ffmpeg-$BIT-${{ matrix.x86_64_level }}-git-$hash.7z ./$BUILD_DIR/$BIT-${{ matrix.x86_64_level }}-w64-mingw32/bin/ffmpeg.exe

      - name: Collecting logs
        if: always()
        run: |
          mkdir -p ${BUILD_DIR}_logs
          cp -fr $(find $BUILD_DIR -type f -iname "*-*.log" -or -wholename "*/ffbuild/config.log") ${BUILD_DIR}_logs || true
          7z a -m0=lzma2 -mx=9 -ms=on logs.7z ${BUILD_DIR}_logs

      - name: Uploading logs
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: mpv-x86_64-${{ matrix.x86_64_level }}-logs
          path: logs.7z
          retention-days: 1

      - name: Uploading x86_64-${{ matrix.x86_64_level }} build
        uses: actions/upload-artifact@master
        with:
          name: mpv-x86_64-${{ matrix.x86_64_level }}
          path: release_${{ matrix.x86_64_level }}/mpv-${{ env.BIT }}*

      - name: Cleaning build directory
        if: always()
        run: |
          rm -rf $BUILD_DIR/mpv*
          ninja -C $BUILD_DIR mpv-fullclean

      - name: Cleaning rust toolchain directory
        if: always()
        run: |
          ninja -C $BUILD_DIR cargo-clean

      - name: Saving clang sysroot cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: |
            clang_root
          key: ${{ secrets.CACHE_VERSION }}-clang_root-${{ github.run_id }}

      - name: Saving repository cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: src_packages
          key: ${{ secrets.CACHE_VERSION }}-repository-${{ github.run_id }}

      - name: Saving ${{ matrix.x86_64_level }} toolchain cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: |
            ${{ env.BUILD_DIR }}
          key: ${{ secrets.CACHE_VERSION }}-clang-${{ matrix.x86_64_level }}_toolchain-${{ github.run_id }}

      - name: Saving release cache
        uses: actions/cache/save@main
        with:
          path: release_${{ matrix.x86_64_level }}
          key: ${{ secrets.CACHE_VERSION }}-release_${{ matrix.x86_64_level }}-${{ github.run_id }}

  release:
    name: Upload releases
    runs-on: ubuntu-latest
    needs: build_mpv
    env:
      GH_TOKEN: ${{ github.token }}
      CURL_RETRIES: "--connect-timeout 60 --retry 999 --retry-delay 5 --retry-all-errors"
      release_v3_key: ${{ secrets.CACHE_VERSION }}-release_v3-${{ github.run_id }}
      release_znver3_key: ${{ secrets.CACHE_VERSION }}-release_znver3-${{ github.run_id }}
    steps:
      - name: Installing dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          git config --global pull.rebase true
          git config --global fetch.prune true

      - uses: actions/checkout@main
        with:
          ref: master

      - name: Loading release_x86_64-v3 cache
        uses: actions/cache/restore@main
        with:
          path: release_v3
          key: ${{ env.release_v3_key }}

      - name: Loading release_x86_64-znver3 cache
        uses: actions/cache/restore@main
        with:
          path: release_znver3
          key: ${{ env.release_znver3_key }}

      - name: Moving archives
        run: |
          mkdir -p release
          mv release_v3/* release || true
          mv release_znver3/* release || true
          du -ah release/*

      - name: Uploading packages to Github release
        id: upload_packages_gh
        if: ${{ github.event_name == 'schedule' || github.event.inputs.github_release == 'true' }}
        continue-on-error: true
        run: |
          tag=$(date "+%Y%m%d-%H%M%S")
          body=$(cat <<END
          ![GitHub release (by tag)](https://img.shields.io/github/downloads/sohnyj/minimal-mpv-winbuild/$tag/total?label=Downloads)

          **Workflow run**: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          END
          )
          id=$(curl -u sohnyj:$GH_TOKEN $CURL_RETRIES -s -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/sohnyj/minimal-mpv-winbuild/releases -d @- <<END | jq -r '.id'
          {
            "tag_name": "$tag",
            "name": "$tag",
            "body": "$(echo ${body//$'\n'/'\n'})"
          }
          END
          )
          for file in release/*.7z; do curl -u sohnyj:$GH_TOKEN $CURL_RETRIES -X POST -H "Accept: application/vnd.github.v3+json" -H "Content-Type: $(file -b --mime-type $file)" https://uploads.github.com/repos/sohnyj/minimal-mpv-winbuild/releases/$id/assets?name=$(basename $file) --data-binary @$file; done

      - name: Pruning tags
        continue-on-error: true
        run: |
          # Keep latest 30 tags/releases
          git fetch --tags
          tag_list=($(git tag | sort -r))
          old=${tag_list[@]:30}
          for tag in ${old[@]}; do
            id=$(curl -u sohnyj:$GH_TOKEN $CURL_RETRIES -s -X GET -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/sohnyj/minimal-mpv-winbuild/releases/tags/$tag | jq -r '.id')
            curl -u sohnyj:$GH_TOKEN $CURL_RETRIES -s -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/sohnyj/minimal-mpv-winbuild/releases/$id
            git tag -d $tag
          done
          git push --tags --prune https://sohnyj:$GH_TOKEN@github.com/sohnyj/minimal-mpv-winbuild

      - name: Delete releases cache
        if: ${{ github.event.inputs.github_release == 'false' || steps.upload_packages_gh.outcome == 'success' }}
        run: |
          curl -u sohnyj:$GH_TOKEN $CURL_RETRIES -s -o /dev/null -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/sohnyj/minimal-mpv-winbuild/actions/caches?key=$release_v3_key
          curl -u sohnyj:$GH_TOKEN $CURL_RETRIES -s -o /dev/null -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/sohnyj/minimal-mpv-winbuild/actions/caches?key=$release_znver3_key
